import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const Neue = localFont({
  src: "../public/fonts/neue.otf",
  variable: "--font-neue"
})

const Gallery = localFont({
  src: "../public/fonts/gallery.otf",
  variable: "--font-gallery"
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${Gallery.variable} ${Neue.variable}`}>{children}</body>
    </html>
  )
}
